[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/JoshElias/nvim.git"
    refreshPeriod = "24h" # Refresh once a week, or manually

[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme.git"
    refreshPeriod = "160h" # Refresh once a week, or manually
