[base]
packages = [
  # Core
  "linux-headers",

  # Shell
  "mise",
  "starship",
  "bat",
  "eza",
  "exfatprogs",
  "dosfstools",
  "rclone",
  "unrar",
  "glow",
  "dust",
  "reflector",
  "plocate",
  "fd",
  "fastfetch",
  "fzf",
  "tlrc-bin",

  # Desktop Environment
  "ly",
  "libnewt",
  "uwsm",
  "brightnessctl",
  "kitty",
  "ghostty",
  "ttf-jetbrains-mono-nerd",
  "ttf-nerd-fonts-symbols-mono",
  "noto-fonts",
  "noto-fonts-emoji",
  "noto-fonts-cjk",
  "noto-fonts-extra",
  "gtk3",
  "brave-bin",
  "proton-pass-bin",
  "proton-mail-bin",
  "cliphist",
  "xdg-ninja",
  "signal-desktop",
  "waybar",
  "hyprpolkitagent",
  "mako",
  "walker-bin",
  "elephant-bin",
  "elephant-desktopapplications-bin",
  "grim",
  "slurp",
  "swappy",
  "btop",
  "rocm-smi-lib",
  "qt6ct",
  "yazi",
  "rose-pine-hyprcursor",
  "hyprland",
  "hyprpaper",
  "hyprshot",
  "hyprsunset",
  "udiskie",
  "imv",
  "wl-clipboard",
  "gparted",
  "gnome-tweaks",
  "gnome-themes-extra",
  "dolphin",
  "localsend-bin",
  "runapp",
  "tree-sitter-cli",
  "impala",

  # Authentication
  "kwallet",
  "kwallet-pam",
  "kwalletmanager",
  "ksshaskpass",

  # Media
  "pipewire",
  "lib32-pipewire",
  "wireplumber",
  "pipewire-audio",
  "pipewire-alsa",
  "pipewire-pulse",
  "pipewire-jack",
  "pwvucontrol",
  "bluez",
  "bluez-utils",
  "bluetui",

  # Productivity
  "xdg-desktop-portal-hyprland",
  "xdg-desktop-portal-kde",
  "gstreamer",
  "discord",
  "slack-desktop",
  "libreoffice-fresh",
  "evince",
  "xournalpp",

  # Entertainment
  "freetube-bin",
  "qbittorrent",
  "tidal-hifi-bin",

  # Graphics
  "mesa",
  "lib32-mesa",

  # Text Editing
  "lazygit",
  "neovim",
]
